import { registerTaskHandlers } from './task-handlers';
import { registerApiKeyHandlers } from './api-key-handlers';
import { registerProviderConfigHandlers } from './provider-config-handlers';
import { registerSettingsHandlers } from './settings-handlers';
import { registerSpeechHandlers } from './speech-handlers';
import { registerDebugHandlers } from './debug-handlers';
import { registerFileHandlers } from './file-handlers';
import { registerSkillsHandlers } from './skills-handlers';
import { registerFavoritesHandlers } from './favorites-handlers';
import { registerConnectorHandlers } from './connector-handlers';
import { registerWorkspaceHandlers } from './workspace-handlers';
import { registerScheduleHandlers } from './schedule-handlers';
import { registerCostHandlers } from './cost-handlers';
import { registerOrchestrationHandlers } from './orchestration-handlers';
import { registerGitHandlers } from './git-handlers';
import { registerSuggestionHandlers } from './suggestion-handlers';
import { registerMarketplaceHandlers } from './marketplace-handlers';
import { registerWebhookHandlers } from './webhook-handlers';
import { registerMemoryHandlers } from './memory-handlers';
import { registerProactiveHandlers } from './proactive-handlers';
import { registerTeamHandlers } from './team-handlers';
import { registerPluginHandlers } from './plugin-handlers';
import { registerMultimodalHandlers } from './multimodal-handlers';
import { registerOfflineHandlers } from './offline-handlers';
import { registerWhatsAppHandlers } from './whatsapp-handlers';
import { registerHuggingFaceHandlers } from './huggingface-handlers';

export function registerIPCHandlers(): void {
  registerTaskHandlers();
  registerApiKeyHandlers();
  registerProviderConfigHandlers();
  registerSettingsHandlers();
  registerSpeechHandlers();
  registerDebugHandlers();
  registerFileHandlers();
  registerSkillsHandlers();
  registerFavoritesHandlers();
  registerConnectorHandlers();
  registerWorkspaceHandlers();
  registerScheduleHandlers();
  registerCostHandlers();
  registerOrchestrationHandlers();
  registerGitHandlers();
  registerSuggestionHandlers();
  registerMarketplaceHandlers();
  registerWebhookHandlers();
  registerMemoryHandlers();
  registerProactiveHandlers();
  registerTeamHandlers();
  registerPluginHandlers();
  registerMultimodalHandlers();
  registerOfflineHandlers();
  registerWhatsAppHandlers();
  registerHuggingFaceHandlers();
}
